### PR TITLE
Fix compiler warnings

### LINKED ISSUE #11: Dangling "else" warnings in Leon's code
There are a lot of compiler warnings (mostly dangling else) that should be cleaned-up.
Need to first create a test suite for the functions in Leon's backtracking lib so that any inadvertent changes that effect functionality will get caught.

### PR DESCRIPTION
**Pull request by fingolfin**
- Fix 'dangling else' warnings (resolves #11)
- Fix check for empty C string
- Fix more compiler warnings

### CODE REVIEW

File: src/leon/src/permut.c [hunk 1]
```diff
@@ -138,20 +139,22 @@ void leftMultiply(
...
 
-   if ( s->invImage )
-      if ( isInvolution( s) )
+   if ( s->invImage ) {
+      if ( isInvolution( s) ) {
          if ( s->invImage != s->image ) {
             freeIntArrayDegree( s->invImage);
             s->invImage = s->image;
          }
          else
```
Comment (dimpase) [inline src/leon/src/permut.c:148]: can we remove this and the next line, they don't do anything, right?

**Review by dimpase — APPROVED** [review]
